nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: James A. Fellows Yates and the nf-core community
  description: Parallelised and automated creation of metagenomic classifier databases
    of different tools
  force: false
  is_nfcore: true
  name: createtaxdb
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - igenomes
  version: 1.1.0dev
lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
