# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "sourmash_create"
description: |
  Sketch the signatures of input genomes (FastA files) in batches and then
  create an index (reference database) from those.
keywords:
  - metagenomics
  - sourmash
  - database
  - build
  - custom
components:
  - sourmash/sketch
  - sourmash/index
input:
  - ch_library:
      type: file
      description: |
        Channel of the grouped DNA FastA files to be sketched. The channel must
        have only one element which is a pair of the database meta information
        and a list of FastA files.
        Structure: [ val(meta), [ path(fasta) ] ]
      pattern: "*.{fasta,fa,fna}"
  - batch_size:
      type: integer
      description: |
        A single value for the batch size to use with sourmash sketch.
        Structure: val(batch_size)
  - kmer_size:
      type: integer
      description: |
        A single value for the k-mer size to use with sourmash index. Typically
        the value 31 is used.
        Structure: val(kmer_size)
output:
  - index:
      type: file
      description: |
        Channel containing a single sourmash index file.
        Structure: [ val(meta), path(db) ]
      pattern: "*.{sbt.zip}"
  - versions:
      type: file
      description: |
        File containing software versions.
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@Midnighter"
maintainers:
  - "@Midnighter"
